// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.EditorExtensions
{
    static class Vsix
    {
        public const string Id = "5fb7364d-2e8c-44a4-95eb-2a382e30fec9";
        public const string Name = "Web Essentials 2015.3";
        public const string Description = "Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015";
        public const string Language = "en-US";
        public const string Version = "3.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "css, javascript, html, json";
    }
}
